### ISSUE TITLE
Error: ENOENT: no such file or directory when building in vercel dev

### ISSUE THREAD

**Issue by fanoway** [vercel-community/rust#83] opened 2023-03-15 02:12 UTC
My handlers build and work properly when using vercel deploy. However using the local vercel dev results in the following error. The target\release\deps directory exists, however the rmetaXXXXX file does not, other files exist with a similair but different name.

`[Error: ENOENT: no such file or directory, scandir 'C:\Users\user-name\Documents\project-name\target\release\deps\rmeta8XbjCX'] {
  errno: -4058,
  code: 'ENOENT',
  syscall: 'scandir',
  path: 'C:\\Users\\user-name\\Documents\\project-name\\target\\release\\deps\\rmeta8XbjCX'
}`

My vercel.json file looks like
`{
    "functions": {
        "api/*/*.rs": {
            "runtime": "vercel-rust@4.0.0-beta.1"
        }
    }
}`

**Comment by ecklf** [comment] 2023-03-15 09:44
Hey there 👋🏻 . Seems like this is a Windows-specific error. Were you using one of the examples or do you have a reproduction repo so I can look into fixing this issue?

**Comment by ecklf** [comment] 2023-03-15 16:57
I think I managed to resolve the issue. The binary name resolving didn't include `.exe` which is added on Windows. In case this issue is not resolved by using `vercel-rust@4.0.0-beta.2` feel free to reopen.

**Comment by fanoway** [comment] 2023-03-15 22:26
Thanks. I am running windows 10 for reference.

I switched to the beta.2 version. and it resulted in the same error.

A bit more info for you. The rmeta dir its looking for does not exist, but there are other rmeta dirs with different names

My repo can be found [here](https://github.com/fanoway/goldilocks)

**Comment by ecklf** [comment] 2023-03-15 22:47
Will have a look at it tomorrow

**Comment by ecklf** [comment] 2023-03-16 08:49
The project was missing a `vercel.json` file (note that the glob in your initial post missed an `*`). Also make sure to add `target` to `.vercelignore` to prevent uploading it.

```json
{
    "functions": {
        "api/**/*.rs": {
            "runtime": "vercel-rust@4.0.0-beta.2"
        }
    }
}
```

After applying the above I could not reproduce the error.
![CleanShot 2023-03-16 at 09 37 52](https://user-images.githubusercontent.com/8146736/225561023-d45d32a1-a199-4c9d-8d75-c5dfb59e4dac.png)

```
$ rustup show
Default host: aarch64-pc-windows-msvc
rustup home:  C:\Users\ecklf\.rustup

stable-aarch64-pc-windows-msvc (default)
rustc 1.68.0 (2c8cc3432 2023-03-06)
```

**Closed** 2024-04-04 08:58 UTC
