### ISSUE TITLE
Example `Experimental API Bundling` Not Working

### ISSUE THREAD

**Issue by afifurrohman-id** [vercel-community/rust#124] opened 2023-09-21 02:11 UTC
# Description
> As Example in `README.md` Have error occurred 

```
error: custom attribute panicked
  --> api/main.rs:12:1
   |
12 | #[bundled_api]
   | ^^^^^^^^^^^^^^
   |
   = help: message: `"api\\_name_"` is not a valid identifier

error[E0425]: cannot find value `handler` in this scope
 --> api/main.rs:5:9
  |
5 |     run(handler).await
  |         ^^^^^^^ not found in this scope
```

**Comment by ecklf** [comment] 2023-09-21 08:01
Did you also include a `handler` function below the macro as documented?

```rust
#[bundled_api]
pub async fn handler(req: Request) -> Result<Response<Body>, Error> {}
```

**Comment by afifurrohman-id** [comment] 2023-09-22 00:50
> Did you also include a `handler` function below the macro as documented?
> 
> ```rust
> #[bundled_api]
> pub async fn handler(req: Request) -> Result<Response<Body>, Error> {}
> ```

in `api/main.rs`?

**Yes, already included**

**Comment by ecklf** [comment] 2023-09-22 07:35
Can you provide a reproduction repo and your system information? Afaik there is a report for it not working on Windows so hence I'm asking.

**Comment by afifurrohman-id** [comment] 2023-09-22 15:57
> Can you provide a reproduction repo and your system information? Afaik there is a report for it not working on Windows so hence I'm asking.

Sorry, i doesn't have that repository.
Just copy paste from example

**I running on windows 11 amd64**

**Comment by ecklf** [comment] 2023-09-27 10:53
Closing then as duplicate of https://github.com/vercel-community/rust/issues/108

**Closed by ecklf** 2023-09-27 10:53 UTC
